I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 119, in script call
    call day0_main from _call_day0_main
  File "game/dev/day0/day0.rpy", line 59, in script
    jump menu1
ScriptError: could not find label 'menu1'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script call
    call script_intro_start from _call_script_intro_start
  File "game/dev/scriptIntro.rpy", line 119, in script call
    call day0_main from _call_day0_main
  File "game/dev/day0/day0.rpy", line 59, in script
    jump menu1
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\ast.py", line 1527, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Iride\Desktop\renpy-6.99.12.4-sdk\renpy\script.py", line 858, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'menu1'.

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
DDLC 365 Day Zero DEMO 0.1.0
